### sign up
POST http://localhost:3000/signup HTTP/1.1

{
  "email": "maani.cr7@gmail.com",
  "password": "123456"
}

### login
POST http://localhost:3000/signin HTTP/1.1
Content-Type: application/json

{
  "email": "maani.cr7@gmail.com",
  "password": "123456"
}


### Analyse
POST http://localhost:3000/analyse HTTP/1.1
Content-Type: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImgzWllvS0ZrTUpxMjJCaS8iLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2dod3V4eXBmcnVlZGN1Z3JuY25mLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI5NWY5YmVkOC1hZmEwLTRiNmUtYThjNy03ZmVlYWU4ZjExZjQiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzUxNjM0MTMyLCJpYXQiOjE3NTE2MzA1MzIsImVtYWlsIjoibWFhbmkuY3I3QGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWwiOiJtYWFuaS5jcjdAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiOTVmOWJlZDgtYWZhMC00YjZlLWE4YzctN2ZlZWFlOGYxMWY0In0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NTE2MzA1MzJ9XSwic2Vzc2lvbl9pZCI6IjNiMjk5NTIyLTJkNDEtNGVhOC1iMGY2LTQwOTU1ZTBmNzZiNyIsImlzX2Fub255bW91cyI6ZmFsc2V9.l2yjlG2e-IEabnpjYp-Nhaii-aiGDGRtNpvioo3rhZ4

{
  "url": "https://www.bbc.com/news/articles/cgkg4m0133po"
}

### Get Analyse
GET http://localhost:3000/ HTTP/1.1
Content-Type: application/json
 